/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FunilRouteImport } from './routes/funil'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizSlugRouteImport } from './routes/quiz.$slug'
import { Route as AuthenticatedPlataformaRouteImport } from './routes/_authenticated/plataforma'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPlataformaCursosRouteImport } from './routes/_authenticated/plataforma.cursos'
import { Route as AuthenticatedAdminVendasRouteImport } from './routes/_authenticated/admin.vendas'
import { Route as AuthenticatedAdminTreinosRouteImport } from './routes/_authenticated/admin.treinos'
import { Route as AuthenticatedAdminQuizVendasRouteImport } from './routes/_authenticated/admin.quiz-vendas'
import { Route as AuthenticatedAdminPlataformaRouteImport } from './routes/_authenticated/admin.plataforma'
import { Route as AuthenticatedAdminFunilVendasRouteImport } from './routes/_authenticated/admin.funil-vendas'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin.cursos'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminAulasRouteImport } from './routes/_authenticated/admin.aulas'
import { Route as AuthenticatedAdminAlunosRouteImport } from './routes/_authenticated/admin.alunos'
import { Route as AuthenticatedPlataformaCursosSlugRouteImport } from './routes/_authenticated/plataforma.cursos.$slug'
import { Route as AuthenticatedAdminCursosIdRouteImport } from './routes/_authenticated/admin.cursos.$id'
import { Route as AuthenticatedAdminQuizVendasEditorIdRouteImport } from './routes/_authenticated/admin.quiz-vendas.editor.$id'

const FunilRoute = FunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSlugRoute = QuizSlugRouteImport.update({
  id: '/quiz/$slug',
  path: '/quiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlataformaRoute = AuthenticatedPlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPlataformaCursosRoute =
  AuthenticatedPlataformaCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedPlataformaRoute,
  } as any)
const AuthenticatedAdminVendasRoute =
  AuthenticatedAdminVendasRouteImport.update({
    id: '/vendas',
    path: '/vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTreinosRoute =
  AuthenticatedAdminTreinosRouteImport.update({
    id: '/treinos',
    path: '/treinos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizVendasRoute =
  AuthenticatedAdminQuizVendasRouteImport.update({
    id: '/quiz-vendas',
    path: '/quiz-vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlataformaRoute =
  AuthenticatedAdminPlataformaRouteImport.update({
    id: '/plataforma',
    path: '/plataforma',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFunilVendasRoute =
  AuthenticatedAdminFunilVendasRouteImport.update({
    id: '/funil-vendas',
    path: '/funil-vendas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/cursos',
    path: '/cursos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAulasRoute = AuthenticatedAdminAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAlunosRoute =
  AuthenticatedAdminAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPlataformaCursosSlugRoute =
  AuthenticatedPlataformaCursosSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedPlataformaCursosRoute,
  } as any)
const AuthenticatedAdminCursosIdRoute =
  AuthenticatedAdminCursosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCursosRoute,
  } as any)
const AuthenticatedAdminQuizVendasEditorIdRoute =
  AuthenticatedAdminQuizVendasEditorIdRouteImport.update({
    id: '/editor/$id',
    path: '/editor/$id',
    getParentRoute: () => AuthenticatedAdminQuizVendasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/funil': typeof FunilRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/plataforma': typeof AuthenticatedPlataformaRouteWithChildren
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz/': typeof QuizIndexRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRouteWithChildren
  '/admin/funil-vendas': typeof AuthenticatedAdminFunilVendasRoute
  '/admin/plataforma': typeof AuthenticatedAdminPlataformaRoute
  '/admin/quiz-vendas': typeof AuthenticatedAdminQuizVendasRouteWithChildren
  '/admin/treinos': typeof AuthenticatedAdminTreinosRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/plataforma/cursos': typeof AuthenticatedPlataformaCursosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/plataforma/cursos/$slug': typeof AuthenticatedPlataformaCursosSlugRoute
  '/admin/quiz-vendas/editor/$id': typeof AuthenticatedAdminQuizVendasEditorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/funil': typeof FunilRoute
  '/plataforma': typeof AuthenticatedPlataformaRouteWithChildren
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz': typeof QuizIndexRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/aulas': typeof AuthenticatedAdminAulasRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRouteWithChildren
  '/admin/funil-vendas': typeof AuthenticatedAdminFunilVendasRoute
  '/admin/plataforma': typeof AuthenticatedAdminPlataformaRoute
  '/admin/quiz-vendas': typeof AuthenticatedAdminQuizVendasRouteWithChildren
  '/admin/treinos': typeof AuthenticatedAdminTreinosRoute
  '/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/plataforma/cursos': typeof AuthenticatedPlataformaCursosRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/plataforma/cursos/$slug': typeof AuthenticatedPlataformaCursosSlugRoute
  '/admin/quiz-vendas/editor/$id': typeof AuthenticatedAdminQuizVendasEditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/funil': typeof FunilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/plataforma': typeof AuthenticatedPlataformaRouteWithChildren
  '/quiz/$slug': typeof QuizSlugRoute
  '/quiz/': typeof QuizIndexRoute
  '/_authenticated/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/_authenticated/admin/aulas': typeof AuthenticatedAdminAulasRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRouteWithChildren
  '/_authenticated/admin/funil-vendas': typeof AuthenticatedAdminFunilVendasRoute
  '/_authenticated/admin/plataforma': typeof AuthenticatedAdminPlataformaRoute
  '/_authenticated/admin/quiz-vendas': typeof AuthenticatedAdminQuizVendasRouteWithChildren
  '/_authenticated/admin/treinos': typeof AuthenticatedAdminTreinosRoute
  '/_authenticated/admin/vendas': typeof AuthenticatedAdminVendasRoute
  '/_authenticated/plataforma/cursos': typeof AuthenticatedPlataformaCursosRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/_authenticated/plataforma/cursos/$slug': typeof AuthenticatedPlataformaCursosSlugRoute
  '/_authenticated/admin/quiz-vendas/editor/$id': typeof AuthenticatedAdminQuizVendasEditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/funil'
    | '/admin'
    | '/plataforma'
    | '/quiz/$slug'
    | '/quiz/'
    | '/admin/alunos'
    | '/admin/aulas'
    | '/admin/configuracoes'
    | '/admin/cursos'
    | '/admin/funil-vendas'
    | '/admin/plataforma'
    | '/admin/quiz-vendas'
    | '/admin/treinos'
    | '/admin/vendas'
    | '/plataforma/cursos'
    | '/admin/'
    | '/admin/cursos/$id'
    | '/plataforma/cursos/$slug'
    | '/admin/quiz-vendas/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/funil'
    | '/plataforma'
    | '/quiz/$slug'
    | '/quiz'
    | '/admin/alunos'
    | '/admin/aulas'
    | '/admin/configuracoes'
    | '/admin/cursos'
    | '/admin/funil-vendas'
    | '/admin/plataforma'
    | '/admin/quiz-vendas'
    | '/admin/treinos'
    | '/admin/vendas'
    | '/plataforma/cursos'
    | '/admin'
    | '/admin/cursos/$id'
    | '/plataforma/cursos/$slug'
    | '/admin/quiz-vendas/editor/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/funil'
    | '/_authenticated/admin'
    | '/_authenticated/plataforma'
    | '/quiz/$slug'
    | '/quiz/'
    | '/_authenticated/admin/alunos'
    | '/_authenticated/admin/aulas'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/funil-vendas'
    | '/_authenticated/admin/plataforma'
    | '/_authenticated/admin/quiz-vendas'
    | '/_authenticated/admin/treinos'
    | '/_authenticated/admin/vendas'
    | '/_authenticated/plataforma/cursos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cursos/$id'
    | '/_authenticated/plataforma/cursos/$slug'
    | '/_authenticated/admin/quiz-vendas/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FunilRoute: typeof FunilRoute
  QuizSlugRoute: typeof QuizSlugRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/funil': {
      id: '/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof FunilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$slug': {
      id: '/quiz/$slug'
      path: '/quiz/$slug'
      fullPath: '/quiz/$slug'
      preLoaderRoute: typeof QuizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plataforma': {
      id: '/_authenticated/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof AuthenticatedPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/plataforma/cursos': {
      id: '/_authenticated/plataforma/cursos'
      path: '/cursos'
      fullPath: '/plataforma/cursos'
      preLoaderRoute: typeof AuthenticatedPlataformaCursosRouteImport
      parentRoute: typeof AuthenticatedPlataformaRoute
    }
    '/_authenticated/admin/vendas': {
      id: '/_authenticated/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AuthenticatedAdminVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/treinos': {
      id: '/_authenticated/admin/treinos'
      path: '/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AuthenticatedAdminTreinosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz-vendas': {
      id: '/_authenticated/admin/quiz-vendas'
      path: '/quiz-vendas'
      fullPath: '/admin/quiz-vendas'
      preLoaderRoute: typeof AuthenticatedAdminQuizVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plataforma': {
      id: '/_authenticated/admin/plataforma'
      path: '/plataforma'
      fullPath: '/admin/plataforma'
      preLoaderRoute: typeof AuthenticatedAdminPlataformaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funil-vendas': {
      id: '/_authenticated/admin/funil-vendas'
      path: '/funil-vendas'
      fullPath: '/admin/funil-vendas'
      preLoaderRoute: typeof AuthenticatedAdminFunilVendasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/aulas': {
      id: '/_authenticated/admin/aulas'
      path: '/aulas'
      fullPath: '/admin/aulas'
      preLoaderRoute: typeof AuthenticatedAdminAulasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alunos': {
      id: '/_authenticated/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AuthenticatedAdminAlunosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/plataforma/cursos/$slug': {
      id: '/_authenticated/plataforma/cursos/$slug'
      path: '/$slug'
      fullPath: '/plataforma/cursos/$slug'
      preLoaderRoute: typeof AuthenticatedPlataformaCursosSlugRouteImport
      parentRoute: typeof AuthenticatedPlataformaCursosRoute
    }
    '/_authenticated/admin/cursos/$id': {
      id: '/_authenticated/admin/cursos/$id'
      path: '/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AuthenticatedAdminCursosIdRouteImport
      parentRoute: typeof AuthenticatedAdminCursosRoute
    }
    '/_authenticated/admin/quiz-vendas/editor/$id': {
      id: '/_authenticated/admin/quiz-vendas/editor/$id'
      path: '/editor/$id'
      fullPath: '/admin/quiz-vendas/editor/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuizVendasEditorIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuizVendasRoute
    }
  }
}

interface AuthenticatedAdminCursosRouteChildren {
  AuthenticatedAdminCursosIdRoute: typeof AuthenticatedAdminCursosIdRoute
}

const AuthenticatedAdminCursosRouteChildren: AuthenticatedAdminCursosRouteChildren =
  {
    AuthenticatedAdminCursosIdRoute: AuthenticatedAdminCursosIdRoute,
  }

const AuthenticatedAdminCursosRouteWithChildren =
  AuthenticatedAdminCursosRoute._addFileChildren(
    AuthenticatedAdminCursosRouteChildren,
  )

interface AuthenticatedAdminQuizVendasRouteChildren {
  AuthenticatedAdminQuizVendasEditorIdRoute: typeof AuthenticatedAdminQuizVendasEditorIdRoute
}

const AuthenticatedAdminQuizVendasRouteChildren: AuthenticatedAdminQuizVendasRouteChildren =
  {
    AuthenticatedAdminQuizVendasEditorIdRoute:
      AuthenticatedAdminQuizVendasEditorIdRoute,
  }

const AuthenticatedAdminQuizVendasRouteWithChildren =
  AuthenticatedAdminQuizVendasRoute._addFileChildren(
    AuthenticatedAdminQuizVendasRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlunosRoute: typeof AuthenticatedAdminAlunosRoute
  AuthenticatedAdminAulasRoute: typeof AuthenticatedAdminAulasRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRouteWithChildren
  AuthenticatedAdminFunilVendasRoute: typeof AuthenticatedAdminFunilVendasRoute
  AuthenticatedAdminPlataformaRoute: typeof AuthenticatedAdminPlataformaRoute
  AuthenticatedAdminQuizVendasRoute: typeof AuthenticatedAdminQuizVendasRouteWithChildren
  AuthenticatedAdminTreinosRoute: typeof AuthenticatedAdminTreinosRoute
  AuthenticatedAdminVendasRoute: typeof AuthenticatedAdminVendasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlunosRoute: AuthenticatedAdminAlunosRoute,
  AuthenticatedAdminAulasRoute: AuthenticatedAdminAulasRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRouteWithChildren,
  AuthenticatedAdminFunilVendasRoute: AuthenticatedAdminFunilVendasRoute,
  AuthenticatedAdminPlataformaRoute: AuthenticatedAdminPlataformaRoute,
  AuthenticatedAdminQuizVendasRoute:
    AuthenticatedAdminQuizVendasRouteWithChildren,
  AuthenticatedAdminTreinosRoute: AuthenticatedAdminTreinosRoute,
  AuthenticatedAdminVendasRoute: AuthenticatedAdminVendasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPlataformaCursosRouteChildren {
  AuthenticatedPlataformaCursosSlugRoute: typeof AuthenticatedPlataformaCursosSlugRoute
}

const AuthenticatedPlataformaCursosRouteChildren: AuthenticatedPlataformaCursosRouteChildren =
  {
    AuthenticatedPlataformaCursosSlugRoute:
      AuthenticatedPlataformaCursosSlugRoute,
  }

const AuthenticatedPlataformaCursosRouteWithChildren =
  AuthenticatedPlataformaCursosRoute._addFileChildren(
    AuthenticatedPlataformaCursosRouteChildren,
  )

interface AuthenticatedPlataformaRouteChildren {
  AuthenticatedPlataformaCursosRoute: typeof AuthenticatedPlataformaCursosRouteWithChildren
}

const AuthenticatedPlataformaRouteChildren: AuthenticatedPlataformaRouteChildren =
  {
    AuthenticatedPlataformaCursosRoute:
      AuthenticatedPlataformaCursosRouteWithChildren,
  }

const AuthenticatedPlataformaRouteWithChildren =
  AuthenticatedPlataformaRoute._addFileChildren(
    AuthenticatedPlataformaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPlataformaRoute: typeof AuthenticatedPlataformaRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPlataformaRoute: AuthenticatedPlataformaRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FunilRoute: FunilRoute,
  QuizSlugRoute: QuizSlugRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
